-- Migration 004: Add validation constraints to form fields
-- Auto-generated by Antigravity IDE

UPDATE public.form_fields SET validation = '{"class": "dob", "max_date": "today", "min_year": 1900}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000001' AND field_key = 'dob';
UPDATE public.form_fields SET validation_regex = '^[6-9]\d{9}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000001' AND field_key = 'mobile_number';
UPDATE public.form_fields SET validation_regex = '^\d{12}$', validation = '{"class": "aadhaar"}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000001' AND field_key = 'aadhaar_number';
UPDATE public.form_fields SET validation_regex = '^[1-9]\d{5}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000001' AND field_key = 'pincode';
UPDATE public.form_fields SET validation = '{"is_integer": true, "min": 0}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000001' AND field_key = 'annual_income';
UPDATE public.form_fields SET validation = '{"is_integer": true, "min": 1}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000001' AND field_key = 'family_member_count';
UPDATE public.form_fields SET validation = '{"class": "dob", "max_date": "today", "min_year": 1900}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000002' AND field_key = 'dob';
UPDATE public.form_fields SET validation_regex = '^[6-9]\d{9}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000002' AND field_key = 'mobile_number';
UPDATE public.form_fields SET validation_regex = '^\d{12}$', validation = '{"class": "aadhaar"}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000002' AND field_key = 'aadhaar_number';
UPDATE public.form_fields SET validation_regex = '^[1-9]\d{5}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000002' AND field_key = 'pincode';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000002' AND field_key = 'family_gross_income';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000002' AND field_key = 'earning_members_count';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000002' AND field_key = 'agricultural_land_acres';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000002' AND field_key = 'residential_flat_sqft';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000002' AND field_key = 'residential_plot_sqyards';
UPDATE public.form_fields SET validation = '{"class": "dob", "max_date": "today", "min_year": 1900}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000003' AND field_key = 'dob';
UPDATE public.form_fields SET validation_regex = '^[6-9]\d{9}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000003' AND field_key = 'mobile_number';
UPDATE public.form_fields SET validation_regex = '^[1-9]\d{5}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000003' AND field_key = 'pincode';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000003' AND field_key = 'income_year_1';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000003' AND field_key = 'income_year_2';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000003' AND field_key = 'income_year_3';
UPDATE public.form_fields SET validation_regex = '^[6-9]\d{9}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000004' AND field_key = 'mobile_number';
UPDATE public.form_fields SET validation = '{"class": "dob", "max_date": "today", "min_year": 1900}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000005' AND field_key = 'dob';
UPDATE public.form_fields SET validation_regex = '^[6-9]\d{9}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000005' AND field_key = 'mobile_number';
UPDATE public.form_fields SET validation_regex = '^\d{12}$', validation = '{"class": "aadhaar"}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000005' AND field_key = 'aadhaar_number';
UPDATE public.form_fields SET validation_regex = '^[1-9]\d{5}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000005' AND field_key = 'pincode';
UPDATE public.form_fields SET validation = '{"class": "dob", "max_date": "today", "min_year": 1900}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000006' AND field_key = 'dob';
UPDATE public.form_fields SET validation_regex = '^[6-9]\d{9}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000006' AND field_key = 'mobile_number';
UPDATE public.form_fields SET validation_regex = '^[1-9]\d{5}$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000006' AND field_key = 'pincode';
UPDATE public.form_fields SET validation_regex = '^[\w\.-]+@[\w\.-]+\.\w+$' WHERE form_id = 'f0000000-0000-0000-0000-000000000006' AND field_key = 'email';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000006' AND field_key = 'emergency_mobile';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000006' AND field_key = 'class_10_percentage';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000006' AND field_key = 'physics_marks';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000006' AND field_key = 'chemistry_marks';
UPDATE public.form_fields SET validation_regex = '^\d+$', validation = '{"is_integer": true}'::jsonb WHERE form_id = 'f0000000-0000-0000-0000-000000000006' AND field_key = 'biology_marks';
